Upgrade D3D12 Agility SDK to 1.721.0-preview
https://devblogs.microsoft.com/directx/announcing-agilitysdk-721-preview-and-more-shader-model-6-10-features
https://www.nuget.org/packages/Microsoft.Direct3D.D3D12/1.721.0-preview

HACK: AllJoyn was deleted because it kept failing with:

    C:\Users\Marijn\Code\TraverseResearch\win32metadata\sources\GeneratorSdk\sdk\sdk.targets(200,5): error : WinRT.AllJoyn:common - ClangSharpPInvokeGenerator failed. Full output at C:\Users\Marijn\Code\TraverseResearch\win32metadata\generation\WinSDK\obj\scratch\common\WinRT.AllJoyn.generation.output.txt. [C:\Users\Marijn\Code\TraverseResearch\win32metadata\generation\WinSDK\Windows.Win32.proj]
    C:\Users\Marijn\Code\TraverseResearch\win32metadata\sources\GeneratorSdk\sdk\sdk.targets(200,5): error : WinRT.AllJoyn:common - C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\include\xmemory:219:5: error: use of undeclared identifier '__builtin_verbose_trap' [C:\Users\Marijn\Code\TraverseResearch\win32metadata\generation\WinSDK\Windows.Win32.proj]